name: Publish Blog Post

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build # Ensure this matches your Astro build command

      - name: Deploy
        run: npm run deploy # Adjust this if you have a specific deploy command or use a service like Vercel/Netlify
